/* N.A.V.I. EroLinks v1.5 — 双状态：观测/控制 + 服装 + 催眠 */

(function(){if(document.getElementById('erolinks-styles'))return;const l=document.createElement('link');l.id='erolinks-styles';l.rel='stylesheet';l.href=new URL('./erolinks.css?v=1.5.0',import.meta.url).href;document.head.appendChild(l);})();

const TABS=[{key:'info',icon:'📋'},{key:'secret',icon:'🔞'},{key:'outfit',icon:'👗',needControl:true},{key:'hypno',icon:'🧠',needControl:true},{key:'sense',icon:'⚡',needControl:true},{key:'log',icon:'📜',needControl:true}];

export class EroLinksView{constructor(app){this.app=app;this.currentView='main';this.activeTab='info';this._loading=false;this._linkedData=null;this._controlMode=false;this._wbRendered=false;this._outfitChanges={};window.VirtualPhone._erolinksView=this;}
_esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
render(){let h;if(this.currentView==='settings')h=this._renderSettings();else if(this.currentView==='linked'&&this._linkedData)h=this._renderLinked();else h=this._renderMain();this.app.phoneShell.setContent(h,'erolinks-'+this.currentView);if(this.currentView==='settings')this._bindSettings();}
goSettings(){this.currentView='settings';this._wbRendered=false;this.render();}
goBack(){this.currentView=this._linkedData?'linked':'main';this.render();}
switchTab(k){if(!this._controlMode&&TABS.find(t=>t.key===k)?.needControl)return;this.activeTab=k;this.render();}
enterControl(){this.activeTab='hypno';this.render();}
activateControl(){this._controlMode=true;this._outfitChanges={};this.render();}

// === 主页 ===
_renderMain(){return`<div class="erolinks-app"><div class="erolinks-bar"><div class="erolinks-bar-btn" onclick="window.VirtualPhone._erolinksView.goSettings()">⚙️</div></div><div class="erolinks-main"><div class="erolinks-link-btn ${this._loading?'loading':''}" onclick="window.VirtualPhone._erolinksView.doLink()"><div class="erolinks-link-ring"></div><div class="erolinks-link-text">${this._loading?'⏳':'LINK'}</div>${this._loading?'<div class="erolinks-link-sub">连接中...</div>':''}</div><div class="erolinks-hint">点击建立身心链接</div></div></div>`;}

// === 已链接 ===
_renderLinked(){const d=this._linkedData;const isCtrl=this._controlMode;return`<div class="erolinks-app${isCtrl?' el-ctrl-mode':''}"><div class="erolinks-bar"><div class="erolinks-bar-btn" onclick="window.VirtualPhone._erolinksView.doLink()">🔄</div><div class="erolinks-bar-btn" onclick="window.VirtualPhone._erolinksView.goSettings()">⚙️</div></div><div class="el-status-bar">${isCtrl?'<span class="el-status-ctrl">🧠 控制状态</span>':'<span class="el-status-obs">👁 观测状态</span>'}</div><div class="el-tabs">${TABS.map(t=>{const locked=t.needControl&&!isCtrl;return`<div class="el-tab${this.activeTab===t.key?' active':''}${locked?' locked':''}" onclick="window.VirtualPhone._erolinksView.switchTab('${t.key}')">${locked?'🔒':t.icon}</div>`;}).join('')}</div><div class="el-tab-content">${this._renderTabContent(d)}</div><div class="el-bottom-bar">${isCtrl?`<button class="el-disconnect-btn" onclick="window.VirtualPhone._erolinksView.disconnect()">🔌 断开链接</button>`:this.activeTab==='hypno'?`<button class="el-ctrl-enter-btn" onclick="window.VirtualPhone._erolinksView.activateControl()">🔓 确认催眠已生效，解锁全部功能</button><button class="el-disconnect-btn" style="margin-top:6px;" onclick="window.VirtualPhone._erolinksView.disconnect()">🔌 断开链接</button>`:`<button class="el-ctrl-enter-btn" onclick="window.VirtualPhone._erolinksView.enterControl()">🧠 进入催眠控制</button><button class="el-disconnect-btn" style="margin-top:6px;" onclick="window.VirtualPhone._erolinksView.disconnect()">🔌 断开链接</button>`}</div></div>`;}
_renderTabContent(d){switch(this.activeTab){case'info':return this._renderInfoTab(d);case'secret':return this._renderSecretTab(d);case'outfit':return this._renderOutfitTab();case'hypno':return this._renderHypnoTab();default:return this._renderPlaceholder();}}

// === 角色信息 ===
_renderInfoTab(d){return`<div class="el-info-scroll"><div class="el-avatar-area"><div class="el-avatar-ring"><div class="el-avatar-inner">${this._esc(d.charName).charAt(0)}</div></div><div class="el-char-name">${this._esc(d.charName)}</div></div><div class="el-info-grid"><div class="el-info-item"><span class="el-info-label">种族</span><span class="el-info-val">${this._esc(d.race||'—')}</span></div><div class="el-info-item"><span class="el-info-label">年龄</span><span class="el-info-val">${this._esc(d.age||'—')}</span></div><div class="el-info-item"><span class="el-info-label">身份</span><span class="el-info-val">${this._esc(d.role||'—')}</span></div><div class="el-info-item"><span class="el-info-label">所属</span><span class="el-info-val">${this._esc(d.affiliation||'—')}</span></div></div><div style="display:flex;gap:6px;margin-bottom:8px;"><div class="el-heartrate-card" style="flex:1;"><div class="el-hr-icon">💓</div><div class="el-hr-value">${this._esc(d.heartRate||'72')}</div><div class="el-hr-unit">BPM</div><div class="el-hr-wave"></div></div><div class="el-heartrate-card" style="flex:1;border-color:rgba(255,140,60,0.15);background:rgba(255,140,60,0.06);"><div class="el-hr-icon" style="color:#ff8c40;">🌡</div><div class="el-hr-value" style="color:#ff8c40;">${this._esc(d.temp||'36.5')}</div><div class="el-hr-unit">°C</div></div></div><div class="el-info-grid"><div class="el-info-item"><span class="el-info-label">状态</span><span class="el-info-val">${this._esc(d.mood||'—')}</span></div><div class="el-info-item"><span class="el-info-label">活动</span><span class="el-info-val">${this._esc(d.activity||'—')}</span></div><div class="el-info-item"><span class="el-info-label">位置</span><span class="el-info-val">${this._esc(d.location||'—')}</span></div><div class="el-info-item"><span class="el-info-label">好感</span><span class="el-info-val">${this._esc(d.favorability||'—')}</span></div></div>${d.thought?`<div class="el-thought"><div class="el-thought-label">💭</div><div class="el-thought-text">${this._esc(d.thought)}</div></div>`:''}</div>`;}

// === 秘密信息 ===
_renderSecretTab(d){return`<div class="el-secret-scroll"><div class="el-secret-section"><div class="el-secret-section-title">🔞 胸穴状态</div><div class="el-secret-grid"><div class="el-secret-item wide"><span class="el-secret-label">胸部</span><span class="el-secret-val">${this._esc(d.breast||'—')}</span></div><div class="el-secret-item wide"><span class="el-secret-label">小穴</span><span class="el-secret-val">${this._esc(d.vulva||'—')}</span></div></div></div><div class="el-secret-section"><div class="el-secret-section-title">📊 性经验</div><div class="el-secret-grid"><div class="el-secret-item"><span class="el-secret-label">经验</span><span class="el-secret-val">${this._esc(d.sexExp||'—')}</span></div><div class="el-secret-item"><span class="el-secret-label">最近</span><span class="el-secret-val">${this._esc(d.lastSex||'—')}</span></div><div class="el-secret-item"><span class="el-secret-label">自慰频率</span><span class="el-secret-val">${this._esc(d.mastFreq||'—')}</span></div><div class="el-secret-item"><span class="el-secret-label">最近自慰</span><span class="el-secret-val">${this._esc(d.lastMast||'—')}</span></div></div></div><div class="el-secret-section"><div class="el-secret-section-title">🌡 生理</div><div class="el-secret-grid"><div class="el-secret-item"><span class="el-secret-label">敏感</span><span class="el-secret-val">${this._esc(d.sensitive||'—')}</span></div><div class="el-secret-item"><span class="el-secret-label">湿润</span><span class="el-secret-val">${this._esc(d.wetness||'—')}</span></div><div class="el-secret-item"><span class="el-secret-label">快感阶段</span><span class="el-secret-val">${this._esc(d.arousal||'—')}</span></div><div class="el-secret-item"><span class="el-secret-label">周期</span><span class="el-secret-val">${this._esc(d.cycle||'—')}</span></div></div></div><div class="el-secret-section"><div class="el-secret-section-title">💭 欲望</div><div class="el-secret-grid"><div class="el-secret-item wide"><span class="el-secret-label">欲望</span><span class="el-secret-val">${this._esc(d.desire||'—')}</span></div><div class="el-secret-item wide"><span class="el-secret-label">幻想</span><span class="el-secret-val">${this._esc(d.fantasy||'—')}</span></div><div class="el-secret-item wide"><span class="el-secret-label">嗜好</span><span class="el-secret-val">${this._esc(d.kink||'—')}</span></div><div class="el-secret-item wide"><span class="el-secret-label">变化</span><span class="el-secret-val">${this._esc(d.bodyChange||'—')}</span></div></div></div></div>`;}

// === 服装 ===
_renderOutfitTab(){const zones=[{id:'head',label:'👒 头部'},{id:'top',label:'👚 上身'},{id:'under',label:'🩲 内衣'},{id:'bottom',label:'👖 下身'},{id:'legs',label:'🦵 腿脚'},{id:'acc',label:'💍 饰品'}];const items=this._linkedData?.outfit||[];return`<div class="el-outfit-scroll">${zones.map(z=>{const zoneItems=items.filter(it=>it.zone===z.id);if(!zoneItems.length)return'';return`<div class="el-outfit-zone"><div class="el-outfit-zone-title">${z.label}</div>${zoneItems.map((it,idx)=>{const key=it.zone+'_'+idx;const ch=this._outfitChanges[key]||{};const removed=ch.action==='remove';const replacing=ch.action==='replace';return`<div class="el-outfit-item${removed?' removed':''}"><div class="el-outfit-info"><span class="el-outfit-name">${this._esc(it.name)}</span></div><div class="el-outfit-actions"><button class="el-outfit-btn${removed?' active':''}" onclick="window.VirtualPhone._erolinksView._toggleOutfit('${key}','remove')">脱下</button><button class="el-outfit-btn${replacing?' active':''}" onclick="window.VirtualPhone._erolinksView._toggleOutfit('${key}','replace')">更换</button></div>${replacing?`<div class="el-outfit-replace"><input class="el-outfit-input" id="el-outfit-input-${key}" placeholder="输入更换为..." value="${this._esc(ch.value||'')}" oninput="window.VirtualPhone._erolinksView._outfitChanges['${key}'].value=this.value"></div>`:''}</div>`;}).join('')}</div>`;}).join('')}${items.length>0?`<div class="el-outfit-bottom"><button class="el-outfit-apply" onclick="window.VirtualPhone._erolinksView._applyOutfit()">📋 确定变更</button></div>`:'<div class="el-placeholder"><div class="el-placeholder-icon">👗</div><div>暂无服装数据</div></div>'}</div>`;}
_toggleOutfit(key,action){const cur=this._outfitChanges[key]||{};if(cur.action===action){delete this._outfitChanges[key];}else{cur.action=action;if(action==='replace'&&!cur.value)cur.value='';this._outfitChanges[key]=cur;}this.render();}
_applyOutfit(){const parts=[];Object.entries(this._outfitChanges).forEach(([key,ch])=>{const[zone,idx]=key.split('_');const items=this._linkedData?.outfit||[];const item=items.find((it,i)=>it.zone===zone&&i===parseInt(idx));if(!item)return;if(ch.action==='remove')parts.push('脱掉 '+item.name);else if(ch.action==='replace'){const to=ch.value?.trim();if(to)parts.push('更换 '+item.name+' 为 '+to);}});if(!parts.length)return;const ta=document.getElementById('send_textarea');if(ta){ta.value=ta.value+(ta.value&&!ta.value.endsWith('\n')?'\n\n':'')+parts.join('，');ta.dispatchEvent(new Event('input',{bubbles:true}));ta.focus();}}

// === 催眠 ===
_renderHypnoTab(){const modes=[{k:'mind_ctrl',n:'意识催眠',d:'完全听从指令的人偶状态',i:'🧿'},{k:'body_ctrl',n:'身体控制',d:'控制身体动作但不控制思想',i:'🦾'},{k:'common_sense',n:'常识改变',d:'将指定内容植入为理所当然的常识',i:'💉'},{k:'sense_ctrl',n:'感官操控',d:'放大或压制特定感官敏感度',i:'👁'},{k:'emotion',n:'情绪注入',d:'注入特定情绪状态',i:'💫'},{k:'trigger',n:'触发词',d:'设定条件反射触发器',i:'🔑'},{k:'memory',n:'记忆修改',d:'植入或抑制特定记忆',i:'📝'},{k:'persona',n:'人格覆盖',d:'在现有性格上叠加临时人格',i:'🎭'}];return`<div class="el-hypno-scroll"><div class="el-hypno-grid">${modes.map(m=>`<div class="el-hypno-card" onclick="window.VirtualPhone._erolinksView._selectHypno('${m.k}')"><div class="el-hypno-card-icon">${m.i}</div><div class="el-hypno-card-name">${m.n}</div><div class="el-hypno-card-desc">${m.d}</div></div>`).join('')}</div></div>`;}
_selectHypno(k){this.app.phoneShell?.showNotification?.('催眠',k+' 开发中...','🧠');}

// === 占位 ===
_renderPlaceholder(){return`<div class="el-placeholder"><div class="el-placeholder-icon">🚧</div><div>功能开发中</div></div>`;}

// === 连接 ===
disconnect(){this._linkedData=null;this._controlMode=false;this._outfitChanges={};this.currentView='main';this.activeTab='info';this.render();}
async doLink(){if(this._loading)return;this._loading=true;this.render();try{const ctx=(typeof SillyTavern!=='undefined'&&SillyTavern.getContext)?SillyTavern.getContext():null;const api=window.VirtualPhone?.apiManager;if(!api)throw new Error('API管理器未就绪');if(!ctx)throw new Error('无法读取酒馆上下文');const wbMsg=await window.VirtualPhone?.worldbookManager?.buildWorldbookMessage('erolinks');const worldbookText=wbMsg?.content||'';const chat=ctx.chat||[];const recentMessages=chat.slice(-10).map(m=>{const name=m.name||'未知';return`${name}: ${String(m.mes||'').substring(0,200)}`;}).join('\n');const systemPrompt=this._getPrompt().split('{{WORLDBOOK}}').join(worldbookText?worldbookText.substring(0,3000):'（无）').split('{{CHAT}}').join(recentMessages||'（无）');const result=await api.callAI([{role:'system',content:systemPrompt},{role:'user',content:'请建立链接并输出结果。'}],{appId:'erolinks',max_tokens:ctx.max_response_length||2048});if(!result?.success)throw new Error(result?.error||'连接失败');const text=String(result.summary||'');const ex=(label)=>{const idx=text.indexOf('【'+label+'】');if(idx===-1)return'';const start=idx+label.length+2;const rest=text.substring(start);const nextBracket=rest.indexOf('\n【');const val=nextBracket>0?rest.substring(0,nextBracket):rest;return val.trim();};this._linkedData={charName:ex('链接角色')||ctx.name2||'未知',race:ex('种族'),age:ex('年龄'),role:ex('身份'),affiliation:ex('所属'),activity:ex('当前活动'),location:ex('所在位置'),favorability:ex('好感度'),heartRate:ex('心率'),temp:ex('体温'),mood:ex('当前状态'),breast:ex('胸部'),vulva:ex('小穴'),sexExp:ex('性经验'),lastSex:ex('最近性行为'),mastFreq:ex('自慰频率'),lastMast:ex('最近自慰'),sensitive:ex('敏感部位'),wetness:ex('湿润状态'),arousal:ex('快感阶段'),cycle:ex('生理周期'),desire:ex('当前欲望'),fantasy:ex('幻想内容'),kink:ex('秘密嗜好'),bodyChange:ex('身体变化'),thought:ex('心理所想'),outfit:this._parseOutfit(ex('服装穿着'))};this.currentView='linked';this.activeTab='info';this._controlMode=false;this._outfitChanges={};}catch(err){console.error('[EroLinks]',err);this.app.phoneShell?.showNotification?.('链接失败',err.message,'❌');}this._loading=false;this.render();}
_parseOutfit(raw){if(!raw)return[];const items=[];const lines=raw.split('\n');let currentZone='';for(const line of lines){const trimmed=line.trim();if(!trimmed)continue;const zoneMatch=trimmed.match(/^【(.+?)】$/);if(zoneMatch){const z=zoneMatch[1];if(z.includes('头'))currentZone='head';else if(z.includes('上')||z.includes('身'))currentZone='top';else if(z.includes('内')||z.includes('胸')||z.includes('裤'))currentZone='under';else if(z.includes('下')||z.includes('裙'))currentZone='bottom';else if(z.includes('腿')||z.includes('脚')||z.includes('袜')||z.includes('鞋'))currentZone='legs';else if(z.includes('饰')||z.includes('手')||z.includes('项'))currentZone='acc';continue;}if(currentZone&&trimmed.startsWith('-')){items.push({zone:currentZone,name:trimmed.replace(/^-\s*/,'').replace(/（.*?）$/,'').trim()});}}return items;}

// === 设置 ===
_renderSettings(){const wbEnabled=window.VirtualPhone?.worldbookManager?.getEnabled?.('erolinks')??true;const promptContent=this._getPrompt();const presetHtml=window.VirtualPhone?.promptManager?.renderPromptPresetControls?.('erolinks','link')||'';return`<div class="erolinks-app"><div class="erolinks-bar"><div class="erolinks-bar-btn" onclick="window.VirtualPhone._erolinksView.goBack()" style="margin-right:auto;">← 返回</div></div><div class="erolinks-scroll"><div class="erolinks-s-body"><div class="erolinks-s-section"><div class="erolinks-s-section-title">🔗 LINK 提示词</div>${presetHtml}<textarea id="erolinks-s-prompt" class="erolinks-s-textarea">${this._esc(promptContent)}</textarea><div class="erolinks-s-btn-row"><button class="erolinks-s-btn erolinks-s-btn-warn" id="erolinks-s-prompt-reset">恢复默认</button><button class="erolinks-s-btn erolinks-s-btn-primary" id="erolinks-s-prompt-save">保存提示词</button></div></div><div class="erolinks-s-section"><div class="erolinks-s-row"><span>📚 注入世界书</span><label class="toggle-switch" style="flex:0 0 auto;"><input type="checkbox" id="erolinks-use-worldbook" ${wbEnabled?'checked':''}><span class="toggle-slider"></span></label></div><div class="phone-prompt-fold erolinks-worldbook-fold" data-default-open="false" style="margin-top:10px;"><div class="phone-prompt-fold-header"><div class="phone-prompt-fold-main"><div class="phone-prompt-fold-title">世界书选择</div><div class="phone-prompt-fold-desc">展开后勾选要注入的酒馆世界书</div></div><i class="fa-solid fa-chevron-right phone-prompt-fold-arrow"></i></div><div class="phone-prompt-fold-content"><div id="erolinks-worldbook-list"></div></div></div></div></div></div></div>`;}
_bindSettings(){const root=this.app.phoneShell.screen;if(!root)return;root.querySelector('#erolinks-s-prompt-save')?.addEventListener('click',()=>{const val=root.querySelector('#erolinks-s-prompt')?.value||'';try{window.VirtualPhone?.promptManager?.updateActivePromptUserPreset('erolinks','link',val);this.app.phoneShell?.showNotification?.('已保存','','✅');}catch(e){this.app.phoneShell?.showNotification?.('保存失败',e.message,'❌');}});root.querySelector('#erolinks-s-prompt-reset')?.addEventListener('click',()=>{if(!confirm('恢复默认提示词？'))return;const content=window.VirtualPhone?.promptManager?.resetPromptToDefault('erolinks','link');const ta=root.querySelector('#erolinks-s-prompt');if(ta&&content)ta.value=content;this.app.phoneShell?.showNotification?.('已恢复','','✅');});window.VirtualPhone?.promptManager?.bindPromptPresetControls?.(document.querySelector('.phone-view-current .erolinks-s-body')||document,'erolinks','link','#erolinks-s-prompt',{notify:(t,m,i)=>this.app.phoneShell?.showNotification?.(t,m,i)});const wbToggle=root.querySelector('#erolinks-use-worldbook');wbToggle?.addEventListener('change',()=>{window.VirtualPhone?.worldbookManager?.setEnabled('erolinks',wbToggle.checked);if(wbToggle.checked&&!this._wbRendered)this._renderWBList();});if(wbToggle?.checked)this._renderWBList();root.querySelectorAll('.phone-prompt-fold').forEach(fold=>{if(fold.dataset.foldInited!=='1'){fold.dataset.foldInited='1';fold.classList.toggle('is-open',String(fold.dataset.defaultOpen||'').toLowerCase()==='true');}});root.querySelectorAll('.phone-prompt-fold-header').forEach(header=>{if(header.dataset.foldBound==='1')return;header.dataset.foldBound='1';header.addEventListener('click',()=>{const fold=header.closest('.phone-prompt-fold');if(fold)fold.classList.toggle('is-open');});});}
_getPrompt(){return window.VirtualPhone?.promptManager?.getPromptForFeature('erolinks','link')||`你是EroLinks身心链接模块。根据世界书和聊天记录判断当前角色并输出：

【链接角色】角色全名
【种族】【年龄】【身份】【所属】
【当前活动】【所在位置】【好感度】
【心率】【体温】【当前状态】
【胸部】实时详细描述≥20字(形态触感充血)
【小穴】实时详细描述≥20字(外唇形态色泽湿润)
【性经验】【最近性行为】【自慰频率】【最近自慰】
【敏感部位】Top3【湿润状态】【上次高潮】【生理周期】
【当前欲望】【幻想内容】【秘密嗜好】【身体变化】
【心理所想】第一人称一句

【服装穿着】
【头部】
- 物品名（颜色/材质简述）
【上身】
- 物品名（颜色/材质简述）
【内衣】
- 胸罩款式（颜色/材质简述）
- 内裤款式（颜色/材质简述）
【下身】
- 物品名（颜色/材质简述）
【腿脚】
- 袜子款式（颜色/材质简述）
- 鞋子款式（颜色/材质简述）
【饰品】
- 物品名（颜色/材质简述）

NSFW分层规则：胸穴、生理、欲望、快感阶段可从上下文推断（默认"未知"）。性经验/性行为/自慰/嗜好/幻想必须聊天中明确说出才填（默认"未知"）。快感阶段从以下8阶选一：平静无波/微有涟漪/暗流涌动/呼吸渐促/酥麻蔓延/难耐轻吟/临界悬丝/决堤溃坝。严禁编造。

上下文：【世界书角色设定】{{WORLDBOOK}}【最近聊天记录】{{CHAT}}`;}
async _renderWBList(){const container=document.getElementById('erolinks-worldbook-list');const mgr=window.VirtualPhone?.worldbookManager;if(!container||!mgr)return;this._wbRendered=true;try{const sources=await mgr.listAvailableWorldbooks({includeEntries:true,force:true});const sel=mgr.getSelectionState('erolinks');if(!sources?.length){container.innerHTML='<div style="font-size:11px;color:#888;padding:6px 0;">未读取到酒馆世界书列表</div>';return;}const sorted=[...sources].sort((a,b)=>{const aS=sel.initialized&&mgr.matchesSelection?.(a,sel.ids)?1:0;const bS=sel.initialized&&mgr.matchesSelection?.(b,sel.ids)?1:0;return bS-aS;});container.innerHTML=sorted.map(s=>{const checked=sel.initialized&&mgr.matchesSelection?.(s,sel.ids)?'checked':'';const active=Number(s.entries?.length||0);const total=Number(s.totalEntries??active);return`<label class="erolinks-wb-item"><input type="checkbox" class="erolinks-wb-cb" value="${this._esc(s.id)}" ${checked}><span class="erolinks-wb-name">${this._esc(s.name)}</span><span class="erolinks-wb-meta">${total>active?active+'/'+total+' 条':active+' 条'}</span></label>`;}).join('');container.querySelectorAll('.erolinks-wb-cb').forEach(cb=>{cb.addEventListener('change',()=>{const ids=[];container.querySelectorAll('.erolinks-wb-cb').forEach(c=>{if(c.checked)ids.push(c.value);});mgr.setSelection('erolinks',ids);});});}catch(e){container.innerHTML='<div style="font-size:11px;color:#d93025;padding:6px 0;">世界书读取失败</div>';}}}
